# Generated by Django 6.0.7 on 2026-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='client@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='client@example.com', max_length=254),
        ),
    ]
