# Generated by Django 6.0.7 on 2026-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactmessage_email_enquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('travel_date', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('adults', models.CharField(default='2', max_length=10)),
                ('children', models.CharField(default='0', max_length=10)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
