# Generated by Django 6.0.7 on 2026-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
